include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

.vars-devel:
  variables:
    MANIFEST_PATH: "build-aux/io.github.wartybix.Constrict.Devel.json"
    FLATPAK_MODULE: "constrict"
    APP_ID: "io.github.wartybix.Constrict.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "constrict-devel.flatpak"

# Build Flatpak for x86_64
flatpak@x86_64:
  extends: ['.flatpak@x86_64', '.vars-devel']

# Build Flatpak for aarch64
flatpak@aarch64:
  extends: ['.flatpak@aarch64', '.vars-devel']
